server.port=${PORT:8081}

# Database Config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/chatapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bunny}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT SECRET
jwt.secret=${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}

# Frontend Resources
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# File Upload Configuration
app.upload-dir=${APP_UPLOAD_DIR:./uploads}
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Optional: Logging for debugging
logging.level.org.springframework.web=WARN 
logging.level.com.chatapp=INFO
